---
title: "ProgrammingAssignment2"
author: "Syed Mohsin Raza"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## makeCacheMatrix fuction

Following is the code chunk which creates the makeCacheMatrix fuction
creating a special "matrix" object that can cache its inverse.

```{r makeCacheMatrix function, echo=TRUE}
makeCacheMatrix <- function(x = matrix()) {
  j <- NULL
  set <- function(y){
  x <<- y
  j <<- NULL
  }
  get <- function()x
  setInverse <- function(inverse) j <<- inverse
  getInverse <- function() j 
  list(set = set, get = get, 
  setInverse = setInverse, 
  getInverse = getInverse)
}
```

## cacheSolve Function

Below code is for cacheSolve Function, which computes the inverse of the special "matrix" returned by makeCacheMatrix 

```{r cacheSolve function, echo=TRUE}
cacheSolve <- function(x, ...) {
  j <- x$getInverse()
  if(!is.null(j)){
  message("Getting Cached Data")
  return(j)
  }
  mat <- x$get()
  j <- solve(mat,...)
  x$setInverse(j)
  j
}
```


